---

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "frr_ospf_hello_and_dead_timers_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Take backup of /etc/frr/ospfd.conf
      copy:
        src: "{{ frr_ospf_conf_file }}"
        dest: "{{ frr_ospf_conf_file_bck }}"
        remote_src: true

    - name: Add dummy interface
      add_dummy_interface:
        switch_name: "{{ inventory_hostname }}"

    - name: Configure hello and dead time interval for eth-7-1
      blockinfile:
        path: "{{ frr_ospf_conf_file }}"
        insertafter: "interface eth-7-1"
        marker: "! {mark} foo"
        block: |
          ip ospf dead-interval 10
          ip ospf hello-interval 5

    - name: Configure hello and dead time interval for eth-17-1
      blockinfile:
        path: "{{ frr_ospf_conf_file }}"
        insertafter: "interface eth-17-1"
        marker: "! {mark} bar"
        block: |
          ip ospf dead-interval 10
          ip ospf hello-interval 5

    - name: Add ospf config in /etc/frr/ospfd.conf
      blockinfile:
        path: "{{ frr_ospf_conf_file }}"
        marker: ""
        block: "{{ lookup('file', '../../files/{{inventory_hostname}}/ospf_interval.conf') }}"

    - name: Restart frr service
      service:
        name: frr
        state: restarted

    - name: Wait few secs for ospf to establish communication
      pause:
        seconds: 35

    - file:
        path: "{{ ospf_log_dir }}"
        state: directory

    - name: Verify frr ospf hello and dead time intervals
      test_ospf_intervals:
        switch_name: "{{ inventory_hostname }}"
        eth_list: "7,17"
        hello_timer: "5"
        dead_timer: "10"
        package_name: "frr"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - include: ../../playbooks/get_goes_version_and_tags.yml

    - name: Restore backup of /etc/frr/ospfd.conf
      copy:
        src: "{{ frr_ospf_conf_file_bck }}"
        dest: "{{ frr_ospf_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ frr_ospf_conf_file_bck }}"
        state: absent

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"

    - name: Restart frr
      service:
        name: frr
        state: restarted


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - name: Print test case result
      debug:
        msg: "Test case result: {{ result.result_status }}"

    - name: Print failure summary
      debug:
        msg: "Failure summary: {{ result.result_detail }}"


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_status.yml
