---

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "bird_bgp_peering_state_propagation_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Add dummy interface
      add_dummy_interface:
        switch_name: "{{ inventory_hostname }}"

    - name: Take backup of /etc/bird/bird.conf
      copy:
        src: "{{ bird_conf_file }}"
        dest: "{{ bird_conf_file_bck }}"
        remote_src: true

    - name: Add bgp config in /etc/bird/bird.conf
      copy:
        src: ../../files/{{inventory_hostname}}/bird_bgp_peering_ebgp_route_advertise.conf
        dest: "{{ bird_conf_file }}"

    - name: Restart bird
      service:
        name: bird
        state: restarted

    - name: Wait few seconds for bgp convergence
      pause:
        seconds: 35

    - file:
        path: "{{ bgp_log_dir }}"
        state: directory

    - name: Verify bird bgp peering state propagation
      test_bird_peering_state_propagation:
        switch_name: "{{ inventory_hostname }}"
        package_name: "bird"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        eth_list: "3,19"
        propagate_switch: "{{ groups['leaf'][1] }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ bgp_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - include: ../../playbooks/get_goes_version_and_tags.yml

    - name: Restore backup of /etc/bird/bird.conf
      copy:
        src: "{{ bird_conf_file_bck }}"
        dest: "{{ bird_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ bird_conf_file_bck }}"
        state: absent

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"

    - name: Restart bird
      service:
        name: bird
        state: restarted


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - name: Print test case result
      debug:
        msg: "Test case result: {{ result.result_status }}"

    - name: Print failure summary
      debug:
        msg: "Failure summary: {{ result.result_detail }}"


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_status.yml
