---

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "gobgp_bgp_state_propagation_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Add dummy interface
      add_dummy_interface:
        switch_name: "{{ inventory_hostname }}"

    - name: Add bgp config in /etc/gobgp/gobgpd.conf
      copy:
        src: "../../files/{{inventory_hostname}}/gobgp_peering_ebgp.conf"
        dest: "{{ gobgp_bgp_conf_file }}"

    - name: Restart gobgpd
      service:
        name: gobgpd
        state: restarted

    - name: Wait few seconds for bgp convergence
      pause:
        seconds: 35

    - name: Add advertise route
      add_remove_route:
        switch_name: "{{ inventory_hostname }}"

    - pause:
        seconds: 5

    - file:
        path: "{{ bgp_log_dir }}"
        state: directory


- hosts: leaf[0]:spine
  become: true
  tasks:
    - name: Verify gobgp state propagation
      test_gobgp_convergence:
        switch_name: "{{ inventory_hostname }}"
        package_name: "gobgpd"
        leaf: "{{ groups['leaf'][1] }}"
        route_present: True
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ bgp_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1


- hosts: leaf[1]
  become: true
  tasks:
    - name: Shutdown interface eth-19-1
      command: "ifconfig eth-19-1 down"

    - name: Shutdown interface eth-3-1
      command: "ifconfig eth-3-1 down"

    - name: Wait 200 seconds for route to become unreachable
      pause:
        seconds: 200


- hosts: leaf[0]:spine
  become: true
  tasks:
    - name: Verify gobgp state propagation
      test_gobgp_convergence:
        switch_name: "{{ inventory_hostname }}"
        package_name: "gobgpd"
        leaf: "{{ groups['leaf'][1] }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ bgp_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1


- hosts: leaf[1]
  become: true
  tasks:
    - name: Bring up interface eth-19-1
      command: "ifconfig eth-19-1 up"

    - name: Bring up interface eth-3-1
      command: "ifconfig eth-3-1 up"

    - name: Wait 40 seconds for route to become reachable
      pause:
        seconds: 40


- hosts: leaf[0]:spine
  become: true
  tasks:
    - name: Verify gobgp state propagation
      test_gobgp_convergence:
        switch_name: "{{ inventory_hostname }}"
        package_name: "gobgpd"
        leaf: "{{ groups['leaf'][1] }}"
        route_present: True
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ bgp_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_version_and_tags.yml

    - name: Remove config file
      file:
        path: "{{ gobgp_bgp_conf_file }}"
        state: absent

    - name: Remove advertise route
      add_remove_route:
        switch_name: "{{ inventory_hostname }}"
        remove: True

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - name: Print test case result
      debug:
        msg: "Test case result: {{ result.result_status }}"

    - name: Print failure summary
      debug:
        msg: "Failure summary: {{ result.result_detail }}"


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_status.yml
