---

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "gobgp_bgp_peering_loop_prevention_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf[1]
  become: true
  tasks:
    - file:
        path: "{{ gobgp_loop_prevention_log_file }}"
        state: touch
        owner: quagga
        group: quagga
        mode: 0640


- hosts: leaf:spine
  become: true
  tasks:
    - name: Add bgp config in /etc/gobgp/gobgpd.conf
      template:
        src: "../../files/{{inventory_hostname}}/gobgp_peering_loop_prevention.conf"
        dest: "{{ gobgp_bgp_conf_file }}"

    - name: Restart gobgpd
      service:
        name: gobgpd
        state: restarted

    - name: Wait few seconds for bgp convergence
      pause:
        seconds: 35

    - name: Add advertise route
      add_remove_route:
        switch_name: "{{ inventory_hostname }}"

    - file:
        path: "{{ bgp_log_dir }}"
        state: directory


- hosts: spine[0]
  become: true
  tasks:
    - name: Restart gobgpd
      service:
        name: gobgpd
        state: restarted


- hosts: leaf[1]
  become: true
  tasks:
    - name: Install pip
      apt:
        name: python-pip
        state: present

    - name: Install mrtparse
      pip:
        name: mrtparse

    - name: Copy mrtparse print all script
      copy:
        src: "../../files/print_all.py"
        dest: "/var/log/print_all.py"
        mode: 0644

    - name: Verify gobgp peering loop prevention
      test_gobgp_bird_loop_prevention:
        switch_name: "{{ inventory_hostname }}"
        log_file: "{{ gobgp_loop_prevention_log_file }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ bgp_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - file:
        path: "{{ gobgp_loop_prevention_log_file }}"
        state: absent


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_version_and_tags.yml

    - name: Remove config file
      file:
        path: "{{ gobgp_bgp_conf_file }}"
        state: absent

    - name: Remove advertise route
      add_remove_route:
        switch_name: "{{ inventory_hostname }}"
        remove: True


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - name: Print test case result
      debug:
        msg: "Test case result: {{ result.result_status }}"

    - name: Print failure summary
      debug:
        msg: "Failure summary: {{ result.result_detail }}"


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_status.yml
