---

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "quagga_bgp_peering_traffic_test_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Take backup of /etc/quagga/bgpd.conf
      copy:
        src: "{{ quagga_bgp_conf_file }}"
        dest: "{{ quagga_bgp_conf_file_bck }}"
        remote_src: true

    - name: Add dummy interface
      add_dummy_interface:
        switch_name: "{{ inventory_hostname }}"

    - name: Add bgp config in /etc/quagga/bgpd.conf
      blockinfile:
        path: "{{ quagga_bgp_conf_file }}"
        marker: ""
        block: "{{ lookup('file', '../../files/{{inventory_hostname}}/bgp_peering_ebgp_route_advertise.conf') }}"

    - name: Restart quagga
      service:
        name: quagga
        state: restarted

    - name: Wait few secs for bgp to establish communication
      pause:
        seconds: 35

    - file:
        path: "{{ bgp_log_dir }}"
        state: directory

    - name: Verify quagga bgp peering ebgp route advertise
      test_bgp_route_advertise:
        switch_name: "{{ inventory_hostname }}"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        package_name: "quagga"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ bgp_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - include: ../../playbooks/get_goes_version_and_tags.yml


- hosts: leaf
  become: true
  tasks:
    - name: Install iperf
      apt:
        name: iperf
        state: present


- hosts: leaf[0]
  become: true
  tasks:
    - name: Copy iperf parallel server shell script
      copy:
        src: ../../files/iperf-parallel-servers
        dest: ~/iperf-parallel-servers.sh
        mode: 0755

    - name: Start iperf server instances
      shell: "~/iperf-parallel-servers.sh 4 server-report"


- hosts: leaf[1]
  become: true
  tasks:
    - name: Initiate iperf client and verify traffic
      verify_iperf_traffic_for_dummy:
        switch_name: "{{ inventory_hostname }}"
        switch_list: "{{ groups['leaf'] }}"
        packet_size_list: "100,500,1500,12000"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ bgp_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1


- hosts: leaf[0]
  become: true
  tasks:
    - name: Stop iperf server instances
      command: "pkill iperf"

    - shell: "rm ~/iperf-parallel-servers.sh"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Restore backup of /etc/quagga/bgpd.conf
      copy:
        src: "{{ quagga_bgp_conf_file_bck }}"
        dest: "{{ quagga_bgp_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ quagga_bgp_conf_file_bck }}"
        state: absent

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"

    - name: Restart quagga
      service:
        name: quagga
        state: restarted


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - name: Print test case result
      debug:
        msg: "Test case result: {{ result.result_status }}"

    - name: Print failure summary
      debug:
        msg: "Failure summary: {{ result.result_detail }}"


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_status.yml
