---

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "quagga_bgp_peering_loop_prevention_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Take backup of /etc/quagga/bgpd.conf
      copy:
        src: "{{ quagga_bgp_conf_file }}"
        dest: "{{ quagga_bgp_conf_file_bck }}"
        remote_src: true

    - name: Add dummy interface
      add_dummy_interface:
        switch_name: "{{ inventory_hostname }}"

    - name: Add bgp config in /etc/quagga/bgpd.conf
      blockinfile:
        path: "{{ quagga_bgp_conf_file }}"
        marker: ""
        block: "{{ lookup('template', '../../files/{{inventory_hostname}}/bgp_peering_loop_prevention.conf') }}"

    - name: Restart quagga
      service:
        name: quagga
        state: restarted

    - name: Wait for few seconds for bgp convergence
      pause:
        seconds: 30

    - file:
        path: "{{ bgp_log_dir }}"
        state: directory

    - file:
        path: "{{ bgp_loop_prevention_log_file }}"
        state: touch
        owner: quagga
        group: quaggavty
        mode: 0640

    - name: Verify quagga bgp peering loop prevention
      test_bgp_loop_prevention:
        switch_name: "{{ inventory_hostname }}"
        leaf_list: "{{ groups['leaf'] }}"
        config_file: "{{ lookup('template', '../../files/{{inventory_hostname}}/bgp_peering_loop_prevention.conf') }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_file: "{{ bgp_loop_prevention_log_file }}"
        log_dir_path: "{{ bgp_log_dir }}"
      register: module_out

    - file:
        path: "{{ bgp_loop_prevention_log_file }}"
        state: absent

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - include: ../../playbooks/get_goes_version_and_tags.yml

    - name: Restore backup of /etc/quagga/bgpd.conf
      copy:
        src: "{{ quagga_bgp_conf_file_bck }}"
        dest: "{{ quagga_bgp_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ quagga_bgp_conf_file_bck }}"
        state: absent

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"

    - name: Restart quagga
      service:
        name: quagga
        state: restarted


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - debug:
        msg: "Test case result: {{ result.result_status }}"

    - debug:
        msg: "Failure summary: {{ result.result_detail }}"
