---

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "frr_isis_basic_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Take backup of /etc/frr/isisd.conf
      copy:
        src: "{{ frr_isis_conf_file }}"
        dest: "{{ frr_isis_conf_file_bck }}"
        remote_src: true

    - name: Update hostname info in isisd.conf
      replace:
        path: "{{ frr_isis_conf_file }}"
        regexp: "^hostname isisd"
        replace: "hostname {{ inventory_hostname }}"

    - name: Add dummy interface
      add_dummy_interface:
        switch_name: "{{ inventory_hostname }}"

    - name: Update interface ip and mtu
      update_eth_ip_mtu:
        switch_name: "{{ inventory_hostname }}"
        config_file: "{{ lookup('file', '../../files/{{inventory_hostname}}/update_eth_ip_mtu') }}"


- hosts: leaf[0]:spine[1]
  become: true
  tasks:
    - name: Configure isis for eth-21-1
      blockinfile:
        path: "{{ frr_isis_conf_file }}"
        insertafter: "interface eth-21-1"
        marker: "! eth-21-1 {mark}"
        block: |
          ip router isis platina


- hosts: leaf[0]:spine[0]
  become: true
  tasks:
    - name: Configure isis for eth-11-1
      blockinfile:
        path: "{{ frr_isis_conf_file }}"
        insertafter: "interface eth-11-1"
        marker: "! eth-11-1 {mark}"
        block: |
          ip router isis platina


- hosts: leaf[1]:spine[1]
  become: true
  tasks:
    - name: Configure isis for eth-5-1
      blockinfile:
        path: "{{ frr_isis_conf_file }}"
        insertafter: "interface eth-5-1"
        marker: "! eth-5-1 {mark}"
        block: |
          ip router isis platina


- hosts: leaf[1]:spine[0]
  become: true
  tasks:
    - name: Configure isis for eth-27-1
      blockinfile:
        path: "{{ frr_isis_conf_file }}"
        insertafter: "interface eth-27-1"
        marker: "! eth-27-1 {mark}"
        block: |
          ip router isis platina


- hosts: leaf:spine
  become: true
  tasks:
    - name: Add isis config in /etc/frr/isisd.conf
      blockinfile:
        path: "{{ frr_isis_conf_file }}"
        marker: ""
        block: "{{ lookup('file', '../../files/{{inventory_hostname}}/isis_basic.conf') }}"
      
    - name: Restart frr
      service:
        name: frr
        state: restarted

    - name: Wait few seconds for isis to establish connection
      pause:
        seconds: 35

    - file:
        path: "{{ isis_log_dir }}"
        state: directory

    - name: Verify frr isis basic
      test_isis_basic:
        switch_name: "{{ inventory_hostname }}"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        package_name: "frr"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ isis_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - include: ../../playbooks/get_goes_version_and_tags.yml

    - name: Restore backup of /etc/frr/isisd.conf
      copy:
        src: "{{ frr_isis_conf_file_bck }}"
        dest: "{{ frr_isis_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ frr_isis_conf_file_bck }}"
        state: absent

    - name: Update interface ip and mtu
      update_eth_ip_mtu:
        switch_name: "{{ inventory_hostname }}"
        config_file: "{{ lookup('file', '../../files/{{inventory_hostname}}/update_eth_ip_mtu') }}"
        revert: True

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"

    - name: Restart frr
      service:
        name: frr
        state: restarted


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - debug:
        msg: "Test case result: {{ result.result_status }}"

    - debug:
        msg: "Failure summary: {{ result.result_detail }}"
